### ISSUE TITLE
Crash because of no permission check before accessing local storage

### ISSUE THREAD

**Issue by sharmas2197** [akmaurya288/LoadingImage#1]
Check for permission to access the storage before accessing it otherwise it will result in a crash that what happening for me

Following conains more info about the crash

```
        Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=5180, uid=10332 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
        at com.akashmaurya.loadingimage.MainActivity.getImagesPath(MainActivity.java:109)
        at com.akashmaurya.loadingimage.MainActivity.showImageFromLocalStorage(MainActivity.java:88)
        at com.akashmaurya.loadingimage.MainActivity.onCreate(MainActivity.java:42)

```

**Comment by sharmas2197** [comment]
**This AsyncTask class should be static or leaks might occur**

**Comment by akmaurya288** [comment]
permission to access the storage before accessing it is added
